[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = ["Juwume <maks.smyslov@yandex.ru>"]

[tool.poetry.dependencies]
python = "^3.9.13"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
